### ISSUE TITLE
Error trying to use DiceRoller inside a Express NodeJs

### ISSUE THREAD

**Issue by mreggiardo** [GreenImp/rpg-dice-roller#211]
**Describe the bug**
Error when trying to parse the data

this is the log
```
TypeError: tail.map(...).flat is not a function
    at peg$c76 (E:\dev\disgruper\node_modules\rpg-dice-roller\lib\umd\bundle.js:18910:10)
    at peg$parseExpression (E:\dev\disgruper\node_modules\rpg-dice-roller\lib\umd\bundle.js:20356:16)
    at peg$parseMain (E:\dev\disgruper\node_modules\rpg-dice-roller\lib\umd\bundle.js:19101:12)
    at peg$parse (E:\dev\disgruper\node_modules\rpg-dice-roller\lib\umd\bundle.js:21126:18)
    at Function.parse (E:\dev\disgruper\node_modules\rpg-dice-roller\lib\umd\bundle.js:21178:16)
    at new DiceRoll (E:\dev\disgruper\node_modules\rpg-dice-roller\lib\umd\bundle.js:21358:44)
    at E:\dev\disgruper\node_modules\rpg-dice-roller\lib\umd\bundle.js:21947:26
    at Array.map (<anonymous>)
    at DiceRoller.roll (E:\dev\disgruper\node_modules\rpg-dice-roller\lib\umd\bundle.js:21946:39)
```

**To Reproduce**
Steps to reproduce the behaviour:
```
            const rpgDiceRoller = require('rpg-dice-roller/lib/umd/bundle.js');
            const roller = new rpgDiceRoller.DiceRoller();
            roller.roll('4d6+1');

            res.json(roller.output)
```

**Environment (please complete the following information):**
node 8

**Additional context**

**Comment by GreenImp** [comment]
I see you're using node 8. I'm afraid that this library [only supports node 12+](https://greenimp.github.io/rpg-dice-roller/guide/#browser-support).

I don't think `flat` existed on that version of node. I'd suggest upgrading to v12 or newer and see if the issue persists.

**Comment by GreenImp** [comment]
I've realised that the setup instructions for CommonJS do mention Node < 12, which does make it seem like it is supported. Sorry for any confusion. I've raised a ticket to update the docs: https://github.com/GreenImp/rpg-dice-roller-docs/issues/24
